pipeline {
    agent any

    tools {
        go 'Go 1.17' // Make sure to configure Go in Jenkins Global Tool Configuration with the name 'Go 1.17'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    // Build your Go application
                    sh 'go build -o goapi'
                }
            }
        }

        stage('Run') {
            steps {
                script {
                    // Run your Go application
                    sh './goapi'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
