pipeline {
    agent any
    tools {
        // Ensure the desired Go version is installed for all stages
        go '1.17'
    }
    srages {
        stage('Build') {
            steps {
                // Build your application
                sh 'go build -o goapi'
            }
        }

        stage('run') {
            steps {
                // Deploy your application
                // This is a placeholder, replace with your actual deployment steps
                sh './goapi' // Assuming it's in the same directory
                sh 'curl localhost:8080/todos'
            }
        }

    }
}